name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  paths:
    - "/src/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Runs unit tests
      uses: actions/setup-node@v4
    - run: npm ci
    - run: npm run test:unit
